version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
