# -----------------------------------------------------------------------------
# PREK CONFIG
# -----------------------------------------------------------------------------
# REFS:
# - DOCS: https://prek.j178.dev/
# - REPO: https://github.com/j178/prek
# - SCHEMA: https://raw.githubusercontent.com/j178/prek/refs/heads/master/prek.schema.json
# -----------------------------------------------------------------------------

"$schema" = "https://raw.githubusercontent.com/j178/prek/refs/heads/master/prek.schema.json"
fail_fast = true

# -----------------------------------------------------------------------------
# BUILTIN ~ BUILTIN ~ BUILTIN ~ BUILTIN ~ BUILTIN ~ BUILTIN ~ BUILTIN ~ BUILTIN
# -----------------------------------------------------------------------------
[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-added-large-files", args = ["--maxkb=100"] },
  { id = "check-case-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
]

# -----------------------------------------------------------------------------
# RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF ~ RUFF
# -----------------------------------------------------------------------------
[[repos]]
repo = "https://github.com/charliermarsh/ruff-pre-commit"
rev = "v0.15.14"
hooks = [{ id = "ruff-format" }, { id = "ruff-check" }]

# -----------------------------------------------------------------------------
# LOCAL ~ LOCAL ~ LOCAL ~ LOCAL ~ LOCAL ~ LOCAL ~ LOCAL ~ LOCAL ~ LOCAL ~ LOCAL
# -----------------------------------------------------------------------------
[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt"
entry = "cargo fmt --all -- --check"
language = "system"
types = ["rust"]
pass_filenames = false
priority = 0

[[repos.hooks]]
id = "cargo-check"
name = "cargo check"
entry = "cargo check --all --"
language = "system"
types = ["rust"]
pass_filenames = false
priority = 0
