[package]
name = "utiles-core"
version.workspace = true
authors.workspace = true
categories = ["science::geo"]
edition.workspace = true
homepage = "https://github.com/jessekrubin/utiles"
keywords = ["map", "geo", "mercator", "tile"]
license.workspace = true
readme = "README.md"
repository = "https://github.com/jessekrubin/utiles"
description = "Map tile utilities aka utiles"

[[bench]]
name = "quadkey"
harness = false

[features]
default = ["pmtiles", "ahash"]
ahash = ["dep:ahash"]
pmtiles = ["dep:fast_hilbert"]

[dependencies]
ahash = { workspace = true, optional = true }
# Not going to get rid of fast_hilbert
fast_hilbert = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[lints]
workspace = true
