[package]
name = "utiles"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Map tile utilities aka utiles"
readme = "README.md"
categories = ["science::geo"]
keywords = ["map", "geo", "mercator", "tile"]
homepage = "https://github.com/jessekrubin/utiles"
repository = "https://github.com/jessekrubin/utiles"

[lib]
name = "utiles"
path = "src/lib.rs"

[[bin]]
name = "utiles"
path = "src/bin.rs"

[dependencies]
utiles-core = { path = "../utiles-core", version = "0.6.0" }
fast_hilbert.workspace = true
geo-types.workspace = true
geojson.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tilejson.workspace = true

# CLI dependencies
tracing.workspace = true
tokio = { workspace = true, features = ["fs"] }
tracing-subscriber = { workspace = true, features = ["fmt", "json", "env-filter", "chrono"] }
clap = { version = "4.5.8", features = ["derive", "color", "wrap_help"] }
globset = "0.4.13"
tokio-stream = "0.1.14"
futures = "0.3.29"
walkdir = "2.4.0"
time = "0.3.36"
# utilesqlite dependencies
rusqlite = { workspace = true, features = ["bundled", "blob", "backup", "functions", "trace"] }
sqlite-hashes = { version = "0.7.3", default-features = false, features = ["hex", "window", "md5", "fnv", "xxhash"] }
imagesize = "0.13.0"
axum = { version = "0.7.5", features = ["tokio", "json", "macros"] }
http-body-util = "0.1.0"
async-trait = "0.1.80"
#async-sqlite = { version = "0.2.2", features = ["bundled", "functions", "trace", ] }
async-sqlite = { workspace = true, features = ["bundled", "functions", "trace", "blob"] }
tower = { version = "0.4.13", features = ["timeout"] }
tower-http = { version = "0.5.1", features = ["trace", "timeout", "add-extension", "util", "request-id"] }
tokio-signal = "0.2.9"
colored = "2.1.0"
chrono = "0.4.38"
num_cpus = "1.16.0"
#image = "0.25.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench"
harness = false
