[package]
name = "utiles"
version = "0.0.1"
edition = "2021"
description = "Map tile utilities aka utiles"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Jesse Rubin <jessekrubin@gmail.com>"]
categories = ["science::geo"]
keywords = ["map", "geo", "mercator", "tile"]
homepage = "https://github.com/jessekrubin/utiles"
repository = "https://github.com/jessekrubin/utiles"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast_hilbert = "2.0.0"
geo-types = "0.7.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
