[package]
name = "utiles-cli"
version = "0.1.0"
edition = "2021"

[lib]
name = "utiles_cli"
path = "src/lib.rs"

[[bin]]
name = "ut"
path = "src/bin.rs"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
rusqlite = { version = "0.29.0", features = ["bundled", "vtab", "blob"] }
tokio = { version = "1.33.0", features = ["full"] }
utiles = { path = "../utiles" }