[package]
name = "utiles-dev"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "utiles_dev"
path = "src/lib.rs"

[[bin]]
name = "utdev"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ndarray = "0.16.1"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

# futures = "0.3.30"
# geo-types.workspace = true
# geojson.workspace = true
# geozero = { version = "0.13.0", features = ["with-mvt", "with-wkb"] }
# rusqlite.workspace = true
# serde.workspace = true
# serde_json.workspace = true
# thiserror.workspace = true
# tilejson.workspace = true
# tracing.workspace = true
# tracing-subscriber.workspace = true
utiles-core = { path = "../utiles-core" }
