[package]
name = "utiles-dev"
version.workspace = true
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "utiles_dev"
path = "src/lib.rs"

[[bin]]
name = "utdev"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
deadpool-sqlite = { version = "0.7.0", features = ["tracing"] }
fast_hilbert.workspace = true
futures = "0.3.29"
geo-types.workspace = true
geojson.workspace = true
geozero = { version = "0.11.0", features = ["with-mvt", "with-wkb"] }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.7.2", features = ["sqlite", "runtime-tokio", "macros"] }
thiserror.workspace = true
tilejson.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utiles = { path = "../utiles" }
utiles-cli = { path = "../utiles-cli" }
utilesqlite = { path = "../utilesqlite" }
